baseURL = ""
languageCode = "en-us"
title = "Lizblog🥧"
theme = "PaperMod"

[params]
  [params.profileMode]
    enabled = true
    title = "Lizosy🥧" 
    subtitle = "Learning never exhausts the mind."
    imageUrl = "profile.png"
    imageTitle = "Liz's Profile Picture"
    imageWidth = 120 # custom size
    imageHeight = 120 # custom size
    [[params.profileMode.buttons]]
      name = "Archive"
      url = "/archive"

  [[params.socialIcons]]
    name = "facebook"
    url = "https://linkedin.com/in/username"
  [[params.socialIcons]]
    name = "Github"
    url = "https://github.com/Lizosy"

#===============================================================#
[languages.en]
languageName = "English"
weight = 1

  [languages.en.menu]
    [[languages.en.menu.main]]
    name = "About"
    url = "about/"
    weight = 1

    [[languages.en.menu.main]]
    name = "Archives"
    url = "archives"
    weight = 2

    [[languages.en.menu.main]]
    name = "Projects"
    url = "projects/"
    weight = 3

    [[languages.en.menu.main]]
    name = "Tags"
    url = "tags/"
    weight = 4

    [[languages.en.menu.main]]
    name = "Search"
    url = "search/"
    weight = 5
