baseURL = ""
languageCode = "en-us"
title = "Lizblog"
theme = "PaperMod"

[params]
  [params.profileMode]
    enabled = true
    title = "Lizblog" 
    subtitle = "This is subtitle"
    imageUrl = "profile.png"
    imageTitle = "Liz's Profile Picture"
    imageWidth = 120 # custom size
    imageHeight = 120 # custom size
    [[params.profileMode.buttons]]
      name = "Archive"
      url = "/archive"
    [[params.profileMode.buttons]]
      name = "Github"
      url = "https://github.com/Lizosy"

  [[params.socialIcons]]
    name = "LinkedIn"
    url = "https://linkedin.com/in/username"
